<img src="./images/shouke_logo.png"
     style="float: right"
     width=100
     style="padding-bottom:100px;"/>
<br>
<br>

<table style="float:center;">
    <tr>
        <td>
            <img src='./images/python-logo.png'width=130>
        </td>
        <td>
            <img src='./images/pandas-logo.png'width=150>
        </td>
    </tr>
</table>

<h1 style='text-align: center;'>Accessing Basic Information of DataFrame </h1>
<h2 style='text-align: center;'>Shouke Wei, Ph.D. Professor</h2>
<h3 style='text-align: center;'>Email: shouke.wei@gmail.com</h3>

## Objective
- how to access basic information of dataframe

In [7]:
# Load the required libraries
import pandas as pd

# Read the data
df = pd.read_csv('./data/gdp_china_clean.csv')

## 1. Access the first few rows of the DataFrame

In [8]:
df.head()

,Unnamed: 0,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
0,0,Guangdong,First,2000,1.074125,8.650,0.314513,1.408147,0.108032,0.976157
1,1,Guangdong,First,2001,1.203925,8.733,0.348443,14.609701,0.132133,1.041519
2,2,Guangdong,First,2002,1.350242,8.842,0.385078,1.830169,0.152108,1.113720
3,3,Guangdong,First,2003,1.584464,8.963,0.481320,2.346735,0.169563,1.238043
4,4,Guangdong,First,2004,1.886462,NaN,0.587002,2.955899,0.185295,1.362765

In [9]:
df.head(3)

,Unnamed: 0,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
0,0,Guangdong,First,2000,1.074125,8.650,0.314513,1.408147,0.108032,0.976157
1,1,Guangdong,First,2001,1.203925,8.733,0.348443,14.609701,0.132133,1.041519
2,2,Guangdong,First,2002,1.350242,8.842,0.385078,1.830169,0.152108,1.113720

## 2. Access the last few rows of the DataFrame

In [10]:
df.tail()

,Unnamed: 0,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
90,90,Henan,Fifth,2014,3.493824,9.436,3.078217,0.399111,0.602869,2.367206
91,91,Henan,Fifth,2015,3.700216,9.480,3.566035,0.459535,0.679935,2.557561
92,92,Henan,Fifth,2016,4.047179,9.532,4.041509,0.471385,0.745374,2.723292
93,93,Henan,Fifth,2017,4.455283,9.392,4.449690,0.000523,0.821552,2.955790
94,94,Henan,Fifth,2018,4.805586,9.360,4.450960,0.551170,0.921773,3.187420

In [11]:
df.tail(2)

,Unnamed: 0,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
93,93,Henan,Fifth,2017,4.455283,9.392,4.44969,0.000523,0.821552,2.95579
94,94,Henan,Fifth,2018,4.805586,9.360,4.45096,0.551170,0.921773,3.18742

## 3. Random selection of DataFrame

In [14]:
df.sample(5)

,Unnamed: 0,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
66,66,Zhejiang,Fourth,2009,2.299035,5.276,1.074232,1.282390,0.265335,2.461081
76,76,Henan,Fifth,2000,0.505299,9.488,0.137774,0.018899,0.044553,0.476626
77,77,Henan,Fifth,2001,0.553301,9.555,0.154406,0.023027,0.050858,0.526742
93,93,Henan,Fifth,2017,4.455283,9.392,4.449690,0.000523,0.821552,2.955790
11,11,Guangdong,First,2011,5.321028,10.505,1.706920,5.899903,0.671240,2.689748

## 4. Access all except few lines

In [15]:
df.head(-2)

,Unnamed: 0,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
0,0,Guangdong,First,2000,1.074125,8.650,0.314513,1.408147,0.108032,0.976157
1,1,Guangdong,First,2001,1.203925,8.733,0.348443,14.609701,0.132133,1.041519
2,2,Guangdong,First,2002,1.350242,8.842,0.385078,1.830169,0.152108,1.113720
3,3,Guangdong,First,2003,1.584464,8.963,0.481320,2.346735,0.169563,1.238043
4,4,Guangdong,First,2004,1.886462,NaN,0.587002,2.955899,0.185295,1.362765
...,...,...,...,...,...,...,...,...,...,...
88,88,Henan,Fifth,2012,2.959931,9.406,2.145000,0.326601,0.500640,2.044262
89,89,Henan,Fifth,2013,3.219130,9.413,2.608746,0.371325,0.558231,2.174067
90,90,Henan,Fifth,2014,3.493824,9.436,3.078217,0.399111,0.602869,2.367206
91,91,Henan,Fifth,2015,3.700216,9.480,3.566035,0.459535,0.679935,2.557561
92,92,Henan,Fifth,2016,4.047179,9.532,4.041509,0.471385,0.745374,2.723292

In [16]:
df.tail(-3)

,Unnamed: 0,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
3,3,Guangdong,First,2003,1.584464,8.963,0.481320,2.346735,0.169563,1.238043
4,4,Guangdong,First,2004,1.886462,NaN,0.587002,2.955899,0.185295,1.362765
5,5,Guangdong,First,2005,2.255737,9.194,0.697793,3.505761,0.228907,1.476994
6,6,Guangdong,First,2006,2.658776,9.442,0.797337,4.202726,0.255334,1.601558
7,7,Guangdong,First,2007,3.177701,9.660,0.929426,4.822350,0.315957,1.769930
...,...,...,...,...,...,...,...,...,...,...
90,90,Henan,Fifth,2014,3.493824,9.436,3.078217,0.399111,0.602869,2.367206
91,91,Henan,Fifth,2015,3.700216,9.480,3.566035,0.459535,0.679935,2.557561
92,92,Henan,Fifth,2016,4.047179,9.532,4.041509,0.471385,0.745374,2.723292
93,93,Henan,Fifth,2017,4.455283,9.392,4.449690,0.000523,0.821552,2.955790
94,94,Henan,Fifth,2018,4.805586,9.360,4.450960,0.551170,0.921773,3.187420

## 5. A summary of DataFrame information
- info(): highlights the total number of rows, names of the columns, their data type, and any missing value

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 10 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Unnamed: 0                                   95 non-null     int64
 1   Province                                     95 non-null     object
 2   GDP ranking                                  95 non-null     object
 3   Year                                         95 non-null     int64
 4   GDP (x10^12CNY)                              95 non-null     float64
 5   population (x10^7 person)                    93 non-null     float64
 6   fixed assets investment (x10^12 CNY)         95 non-null     float64
 7   total imports and exports (x10^8CNY)         95 non-null     float64
 8   fiscal expenditure(x10^12CNY)                95 non-null     float64
 9   urban disposal income per capita (x10^4CNY)  95 non-null     float64
dtypes: float64(6), int64(2), object(2)
memory usage: 7.5+ KB

## 6. Access one column's date type

In [20]:
df['Year  '].dtype

dtype('int64')

## 7. Check the column names

In [19]:
df.columns

Index(['Unnamed: 0', 'Province', 'GDP ranking ', 'Year  ', 'GDP (x10^12CNY)',
       'population (x10^7 person)', 'fixed assets investment (x10^12 CNY)',
       'total imports and exports (x10^8CNY)', 'fiscal expenditure(x10^12CNY)',
       'urban disposal income per capita (x10^4CNY)'],
      dtype='object')

## 8. Check the shape of the DataFrame

In [21]:
df.shape

(95, 10)

## 9. Generate a summary of some descriptive statistics

In [22]:
df.describe()

,Unnamed: 0,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
count,95.000000,95.000000,95.000000,93.000000,95.000000,95.000000,95.000000,95.000000
mean,47.000000,2009.000000,3.456443,8.321032,1.914406,2.122045,0.448604,2.204282
std,27.568098,5.506283,2.365092,1.802813,1.558411,2.300531,0.366626,1.225310
min,0.000000,2000.000000,0.505299,4.680000,0.137774,0.000523,0.043130,0.476626
25%,23.500000,2004.000000,1.425301,7.588000,0.588736,0.412089,0.138071,1.159632
50%,47.000000,2009.000000,3.093328,9.194000,1.418528,1.523541,0.326767,1.994583
75%,70.500000,2014.000000,4.956176,9.488000,3.056260,3.054562,0.700097,3.059870
max,94.000000,2018.000000,9.727777,10.999000,5.521350,14.609701,1.572926,5.557430

In [23]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,95.0,47.000000,27.568098,0.000000,23.500000,47.000000,70.500000,94.000000
Year,95.0,2009.000000,5.506283,2000.000000,2004.000000,2009.000000,2014.000000,2018.000000
GDP (x10^12CNY),95.0,3.456443,2.365092,0.505299,1.425301,3.093328,4.956176,9.727777
population (x10^7 person),93.0,8.321032,1.802813,4.680000,7.588000,9.194000,9.488000,10.999000
fixed assets investment (x10^12 CNY),95.0,1.914406,1.558411,0.137774,0.588736,1.418528,3.056260,5.521350
total imports and exports (x10^8CNY),95.0,2.122045,2.300531,0.000523,0.412089,1.523541,3.054562,14.609701
fiscal expenditure(x10^12CNY),95.0,0.448604,0.366626,0.043130,0.138071,0.326767,0.700097,1.572926
urban disposal income per capita (x10^4CNY),95.0,2.204282,1.225310,0.476626,1.159632,1.994583,3.059870,5.557430

In [24]:
df.to_csv('./results/describe_result.csv')