<img src="./images/shouke_logo.png"
     style="float: right"
     width=100
     style="padding-bottom:30px;"/>
<br>
<br>

<table style="float:center;">
    <tr>
        <td>
            <img src='./images/python-logo.png'width=130>
        </td>
        <td>
            <img src='./images/pandas-logo.png'width=150>
        </td>
    </tr>
</table>

<h1 style='text-align: center;'>Reading Data and Saving DataFrame</h1>
<h2 style='text-align: center;'>Shouke Wei, Ph.D. Professor</h2>
<h3 style='text-align: center;'>Email: shouke.wei@gmail.com</h3>

## Objective
- how to read data into Pandas Dataframe
- how to save Pandas DataFrame as a .CSV file

## 1. Import required packages

In [57]:
import pandas as pd

In [58]:
print(f'Pandas Version: {pd.__version__}')

Pandas Version: 1.3.4

## 2. Read data into DataFrame
### (1) Read local .CSV file

In [59]:
df = pd.read_csv("./data/gdp_china.csv")

In [60]:
df.head()

,Province,GDP ranking,Year,GDP (x10^8CNY),population (x10^4 person),fixed assets investment (x10^8 CNY),total imports and exports (CNY),fiscal expenditure （x10^9CNY),urban disposal income per capita (CNY）
0,Guangdong,1,2000,10741.25,8650,3145.13,140814657,1080.32,9761.57
1,Guangdong,1,2001,12039.25,8733,3484.43,146097010,1321.33,10415.19
2,Guangdong,1,2002,13502.42,8842,3850.78,183016893,1521.08,11137.20
3,Guangdong,1,2003,15844.64,8963,4813.20,234673452,1695.63,12380.43
4,Guangdong,1,2004,18864.62,9111,5870.02,295589873,1852.95,13627.65

### (2) Read online data

In [62]:
url ='https://raw.githubusercontent.com/WEIAI-TECH/python-data-analysis-modelling_beginner/main/data/gdp_china_clean.csv'
df2 = pd.read_csv(url)

In [63]:
df2.head()

                                                                                                                                                                                Table: Social Economic Development Data of First 5 Big Provinces by GDP \t\t\t\t\t\t
Province  GDP ranking  Year   GDP (x10^12CNY) population (x10^7 person) fixed assets investment (x10^12 CNY) total imports and exports (x10^8CNY) fiscal expenditure(x10^12CNY)        urban disposal income per capita (x10^4CNY)
Guangdong First        2000   1.074125        8.65                      0.314513                             1.40814657                           0.108032                                                                0.976157
                       2001   1.203925        8.733                     0.348443                             14.609701                            0.132133                                                                1.041519
                       2002   1.350242        8.842                     0.385078                             1.83016893                           0.152108                                                                 1.11372
                       2003   1.584464        8.963                     0.48132                              2.34673452                           0.169563                                                                1.238043

In [64]:
df2.tail()

                                                                                    Table: Social Economic Development Data of First 5 Big Provinces by GDP \t\t\t\t\t\t
Gongdong  Statistical Yearbooks (2001  2002-2019)\t\t\t\t\t NaN NaN NaN NaN NaN NaN                                                NaN
Jiangsu  Statistical Yearbooks (2001   2002-2019)\t\t\t\t\t NaN NaN NaN NaN NaN NaN                                                NaN
Shangdong Statistical Yearbooks (2001  2002-2019)\t\t\t\t\t NaN NaN NaN NaN NaN NaN                                                NaN
Zhejiang Statistical Yearbooks (2001   2002-2019)\t\t\t\t\t NaN NaN NaN NaN NaN NaN                                                NaN
Henan  Statistical Yearbooks (2001     2002-2019)\t\t\t\t\t NaN NaN NaN NaN NaN NaN                                                NaN

There is a number of pandas commands to read and write other data formats, such as:
```python
pd.read_excel('filename.xlsx',sheet_name='Sheet1', index_col=None, na_values=['NA'])
pd.read_stata('filename.dta')
pd.read_sas('filename.sas7bdat')
pd.read_hdf('filename.h5','df')

...
```
Note: The above command has many optional arguments to fine-tune the data import process.

More information can be refers to https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

### (4) Skip rows from top

In [65]:
df2 = pd.read_csv(url,skiprows = 2)

In [66]:
df2.head()

,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
0,Guangdong,First,2000.0,1.074125,8.650,0.314513,1.408147,0.108032,0.976157
1,Guangdong,First,2001.0,1.203925,8.733,0.348443,14.609701,0.132133,1.041519
2,Guangdong,First,2002.0,1.350242,8.842,0.385078,1.830169,0.152108,1.113720
3,Guangdong,First,2003.0,1.584464,8.963,0.481320,2.346735,0.169563,1.238043
4,Guangdong,First,2004.0,1.886462,NaN,0.587002,2.955899,0.185295,1.362765

### (5) Skip rows from bottom / footer

In [68]:
df2 = pd.read_csv(url,skipfooter =7,engine='python')

In [69]:
df2.tail()

                                                             Table: Social Economic Development Data of First 5 Big Provinces by GDP \t\t\t\t\t\t
Henan Fifth 2014 3.493824 9.436 3.078217 0.39911129 0.602869                                           2.367206
            2015 3.700216 9.48  3.566035 0.45953484 0.679935                                           2.557561
            2016 4.047179 9.532 4.041509 0.47138464 0.745374                                           2.723292
            2017 4.455283 9.392 4.44969  0.00052339 0.821552                                            2.95579
            2018 4.805586 9.36  4.45096  0.55117    0.921773                                            3.18742

In [70]:
df2 = pd.read_csv(url,skiprows=2,skipfooter =7,engine='python')

In [71]:
df2.tail()

,Province,GDP ranking,Year,GDP (x10^12CNY),population (x10^7 person),fixed assets investment (x10^12 CNY),total imports and exports (x10^8CNY),fiscal expenditure(x10^12CNY),urban disposal income per capita (x10^4CNY)
90,Henan,Fifth,2014,3.493824,9.436,3.078217,0.399111,0.602869,2.367206
91,Henan,Fifth,2015,3.700216,9.480,3.566035,0.459535,0.679935,2.557561
92,Henan,Fifth,2016,4.047179,9.532,4.041509,0.471385,0.745374,2.723292
93,Henan,Fifth,2017,4.455283,9.392,4.449690,0.000523,0.821552,2.955790
94,Henan,Fifth,2018,4.805586,9.360,4.450960,0.551170,0.921773,3.187420

## 3 Save DataFrame

In [72]:
df2.to_csv('./data/gdp_china_clean.csv', index=False)